name: Swift

on: [push]

jobs:
  build-linux:
    name: Build Linux
    strategy:
      matrix:
        swift: [5.6.3, 5.7]
    runs-on: ubuntu-20.04
    steps:
    - name: Install Swift
      uses: slashmo/install-swift@v0.3.0
      with:
        version: ${{ matrix.swift }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Swift Version
      run: swift --version
    - name: Install dependencies
      run: sudo apt-get install -y libavahi-compat-libdnssd-dev
    - name: Build (Debug)
      run: swift build -c debug
    - name: Build (Release)
      run: swift build -c release
    - name: Test (Debug)
      run: swift test --configuration debug
    - name: Test (Release)
      run: swift test --configuration release -Xswiftc -enable-testing
